config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"

  resources :restaurants
  resources :dishes
  post 'addresses/fetch', to: 'addresses#fetch', as: 'fetch_address'

  resources :sessions, only: [:new, :create, :destroy] do
    get :failure, on: :collection
  end
  get 'auth/failure', to: 'sessions#failure'
  get 'auth/google_oauth2', as: 'google_sign_in'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'sign_out'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :restaurant

  def self.create_from_full(full_address, options)
    create(parts_from_full(full_address).merge(options))
  end

  def self.parts_from_full(full_address)
    m = full_address.match(
      /(?<address_1>[^,]+), (?<city>[^,]+), (?<state>\w{2}) ?(?<zip>[\d\-]+)?/i
    )
    {
      address_1: m[:address_1],
      city:      m[:city],
      state:     m[:state],
      zip:       m[:zip],
    }
  end

  def formatted_address
    "#{address_1}, #{city}"
  end
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :category, polymorphic: true
  validates :category, presence: true
  has_many :ratings, dependent: :destroy

  accepts_nested_attributes_for :ratings
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category, polymorphic: true
  validates :category, presence: true
  has_many :ratings
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :dish
  # validates :dish, presence: true

  scope :for_restaurant, -> (restaurant) {
    where(dish_id: restaurant.dishes.select(:id))
  }

  scope :for_user, -> (user) { where(user_id: user.id) }
  scope :not_for_user, -> (user) {
    user ? where.not(user_id: user.id) : all
  }

  def self.calculate_average
    average(:value)
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :dishes, as: :category
  has_many :ratings, through: :dishes
  has_one :address, dependent: :destroy

  delegate :formatted_address, to: :address, allow_nil: true

  scope :with_dish_count, -> {
    left_join_dishes.group(:id)
      .select('restaurants.*',
        'count(dishes.id) as dish_count')
      .order('dish_count desc')
  }

  scope :left_join_dishes, -> {
    joins("LEFT JOIN dishes ON dishes.category_id = restaurants.id " \
          "AND dishes.category_type = 'Restaurant'")
  }

  def average_rating
    ratings.calculate_average
  end
end

app/models/user.rb
require 'user_authentication'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  has_many :ratings
  has_many :user_auths

  attr_accessor :remember_token

  def self.from_omniauth(auth_data)
    user = find_or_initialize_by(auth_uid: auth_data['uid'],
                                 auth_provider: auth_data['provider'])
    user.name  = auth_data['info']['name']
    user.email = auth_data['info']['email']

    user.save! if user.new_record? || user.changed?
    user
  end

  def remember
    self.remember_token = UserAuthentication.new_token
    update_attribute :remember_digest, UserAuthentication.digest(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end
end

app/controllers/addresses_controller.rb
require 'address_lookup'

class AddressesController < ApplicationController
  def fetch
    restaurant = Restaurant.find(params[:restaurant_id])
    result = AddressLookup.find(name: restaurant.name, city: params[:city])
    return render text: "Google couldn't find this one. Sorry!" unless result

    addr = Address.create_from_full(result, restaurant_id: restaurant.id)
    render text: addr.formatted_address
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
    @restaurant = Restaurant.find params[:restaurant_id]
    @dish = @restaurant.dishes.new
    @rating = @dish.ratings.new
  end

  def create
    # todo validation errors
    Rating.for_user(current_user).scoping do
      @dish = Dish.create!(dish_params)
    end
    raise unless @dish.ratings.first.value
    redirect_to restaurant_path(@dish.category)
  end

  private

  def dish_params
    params.require(:dish).permit!
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.with_dish_count.includes(:address).map do |r|
      r.attributes.symbolize_keys!.merge(address: r.formatted_address)
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    if current_user
      @your_dishes = Rating.for_restaurant(@restaurant).for_user(current_user).map do |rating|
        { name: rating.dish.name, rating: rating.value }
      end
    end
    @all_dishes = Rating.for_restaurant(@restaurant).not_for_user(current_user).map do |rating|
      { name: rating.dish.name, rating: rating.value }
    end
  end

  def create
    if (r = Restaurant.create(restaurant_params))
      redirect_to restaurant_path(r)
      flash[:success] = "Successfully created #{r.name}"
    else
      flash[:error] = "There was an error creating the new restaurant"
      redirect_to root_path
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:forwarding_url] = request.referer
    redirect_to google_sign_in_path
  end

  def create
    begin
      @user = User.from_omniauth(request.env['omniauth.auth'])
      log_in @user
      remember @user
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end
    redirect_to session[:forwarding_url] || root_path
  end

  def destroy
    log_out
    forget @user
    flash[:info] = "Successfully logged out"
    redirect_to request.referer || root_path
  end

  def failure
    log_out
    flash[:info] = "There was an error while trying to authenticate you..."
    redirect_to request.referer || root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def self.image_for_rating(number)
    face = case number
    when 1 then "confounded"
    when 2 then "persevere"
    when 3 then "confused"
    when 4 then "smirk"
    when 5 then "yum"
    when 6 then "heart_eyes"
    end
    emojify(":#{face}:")
  end

  def self.emojify(content)
    content.to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img
          alt="#$1"
          src="#{ActionController::Base.helpers.image_path("emoji/#{emoji.image_filename}")}"
          style="vertical-align:middle; height: 2em; width: 2em;"
          class="emoji-icon" />).squish
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/helpers/sessions_helper.rb
require 'user_authentication'

module SessionsHelper

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && UserAuthentication.correct_token?(user, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    @user.remember
    cookies.permanent.signed[:user_id] = @user.id
    cookies.permanent[:remember_token] = @user.remember_token
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def forget(user)
    @user.forget if @user
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

end

app/views/dishes/new.html.haml
%h2
  New Dish for
  = @restaurant[:name]
= form_for @dish do |f|
  = f.hidden_field :category_id
  = f.hidden_field :category_type
  .form-group
    %input#dish_name.form-control{ placeholder: "Dish Name", name: "dish[name]" }
  .form-group
    = f.fields_for :ratings do |ff|
      .flex-grid
        .flex-grid-cell
          %label.emoji-labels
            = ff.radio_button :value, '1', onchange: 'update_checked(this)'
            %div= EmojiHelper.image_for_rating 1
        .flex-grid-cell
          %label.emoji-labels
            = ff.radio_button :value, '2', onchange: 'update_checked(this)'
            %div= EmojiHelper.image_for_rating 2
        .flex-grid-cell
          %label.emoji-labels
            = ff.radio_button :value, '3', onchange: 'update_checked(this)'
            %div= EmojiHelper.image_for_rating 3
        .flex-grid-cell
          %label.emoji-labels
            = ff.radio_button :value, '4', onchange: 'update_checked(this)'
            %div= EmojiHelper.image_for_rating 4
        .flex-grid-cell
          %label.emoji-labels
            = ff.radio_button :value, '5', onchange: 'update_checked(this)'
            %div= EmojiHelper.image_for_rating 5
        .flex-grid-cell
          %label.emoji-labels
            = ff.radio_button :value, '6', onchange: 'update_checked(this)'
            %div= EmojiHelper.image_for_rating 6
  = f.submit "Submit", class: "btn btn-raised btn-primary btn-block"

:css
  .flex-grid {
    text-align: center;
    height: 60px;
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
  }
  .flex-grid-cell { flex: 1; }
  .emoji-labels input[type=radio] {
    display: none;
  }
  .grayscale {
    -webkit-filter: grayscale(100%);
    filter: grayscale(100%);
  }

:javascript
  function update_checked(cb) {
    $('.emoji-labels').addClass('grayscale');
    $(cb).parent().removeClass('grayscale');
  }

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Favorites
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ name: "apple-mobile-web-app-capable", content: "yes" }
    %meta{ name: "apple-mobile-web-app-status-bar-style", content: "black-translucent" }
    %link{ rel: "apple-touch-icon", href: "/apple-touch-icon.png" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1" }
    %meta{ name: "google-site-verification", content: "oDIhveA9gNQsk5qjWXrpKPvTopaYQhswL_ir3nCzJ1E" }

    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Roboto:300,400,500,700"
    = stylesheet_link_tag "//fonts.googleapis.com/icon?family=Material+Icons"

  %body
    = render 'shared/ios_native_status_bar'
    = render 'shared/navbar'
    .container
      - flash.each do |type, message|
        .alert{ class: "alert-#{type}" }= message

      = yield

app/views/restaurants/_fetch_address_form.html.haml
#fetch-address-form
  #fetch-step-1
    Fetch address from Google
  #fetch-step-2{ style: "display: none; "}
    What city?
    %button.btn.btn-sm.btn-raised.btn-info.city Chicago
    %button.btn.btn-sm.btn-raised.btn-info.city New York


:javascript
  $fetch_step_1 = $('#fetch-step-1')
  $fetch_step_2 = $('#fetch-step-2')

  $fetch_step_1.on('click', function() {
    $fetch_step_1.hide();
    $fetch_step_2.show();
  })

  $('#fetch-step-2 button.city').on('click', function() {
    $('#fetch-address-form').load('#{fetch_address_path}',
      {
        restaurant_id: '#{@restaurant.id}',
        city: $(this).text()
      }
    )
  })

app/views/restaurants/index.html.haml
- content_for(:navicon){ "sentiment_very_satisfied" }

.list-group#restaurants-filtered
  - @restaurants.each do |restaurant|
    .filter-row
      = link_to restaurant_path(restaurant[:id]), class: "list-group-item", style: "" do
        .row-content
          .list-group-item-heading.filter-on= restaurant[:name]
          .list-group-item-text= restaurant[:address]
          %span.badge.action-secondary= restaurant[:dish_count]
      .list-group-separator
= form_for :restaurant, url: restaurants_path, html: { id: "add-new-place" } do |f|
  = f.hidden_field :name, class: "name-field"
  %button#add-new-place.btn.btn-raised.btn-info.btn-block
    Add
    %span.name-field
    !

app/views/restaurants/show.html.haml
.aligned-row
  .restaurant-name{ style: "flex: 4; -webkit-flex: 4;" }
    %h2{ style: "display: inline-block;" }= @restaurant[:name]
  - if current_user
    .add-button
      = link_to new_dish_path(restaurant_id: @restaurant[:id]), class: "btn btn-fab btn-fab-mini btn-info pull-right" do
        %i.material-icons add
%p
  - if @restaurant.address
    = @restaurant.formatted_address
  - else
    = render 'fetch_address_form'

.spacer

- if @your_dishes.present?
  %h5 You
  %table.table.table-striped.table-hover
    %tbody
      - @your_dishes.each do |dish|
        %tr
          %td= dish[:name]
          %td= EmojiHelper.image_for_rating dish[:rating]
- elsif !current_user
  = link_to "Log in here", new_session_path
  to start adding your own ratings!
- else
  You haven't rated anything here! Go ahead and add something using the button above.

.spacer

- if @all_dishes.present?
  %h5 Everybody else
  %table.table.table-striped.table-hover
    %tbody
      - @all_dishes.each do |dish|
        %tr
          %td= dish[:name]
          %td= EmojiHelper.image_for_rating dish[:rating]
- else
  No one else has rated things here!

:css
  .aligned-row {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display:         flex;
    align-items: center;
  }
  .add-button {
    flex: 1;
    -webkit-flex: 1;
    align-self: center;
    -webkit-align-self: center;
  }
  .spacer {
    width: 100%;
    height: 20px;
  }

app/views/shared/_ios_native_status_bar.html.haml
#ios-native-bar.navbar-inverse
#ios-native-bar-placeholder.navbar-inverse

:css
  #ios-native-bar {
    width: 100%;
    height: 20px;
    display: none;
    position: fixed;
    z-index: 1;
  }
  #ios-native-bar-placeholder {
    width: 100%;
    height: 20px;
    display: none;
  }
  .snackbar-content, .snackbar-content > * {
    max-width: 100%;
  }

:javascript
  $(document).on('ready page:load', function () {
    if (window.navigator.standalone) {
      $("#ios-native-bar").show();
      $("#ios-native-bar-placeholder").show();
    } else if (navigator.platform.indexOf("iPhone") != -1) {
      $.snackbar({
        content: "To use Favorites like a normal app, tap the share button below (in the middle, with the up arrow), and tap 'Add To Home Screen'",
        timeout: 30000
      })
    }
  })
  $("#ios-native-bar").click(function() {
    $("html, body").animate({ scrollTop: 0 });
  });

app/views/shared/_navbar.html.haml
.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %a.navbar-brand{:href => "javascript:window.history.go(-1);"}
        %i.material-icons
          = yield(:navicon).presence || "keyboard_arrow_left"
      %a.navbar-brand{:href => root_path } Favorites!
      - if params[:action] == "index"
        %form.navbar-form.navbar-brand.navbar-right.pull-right{ style: "margin: 0;"}
          .form-group
            %input#search-filter.form-control.col-md-8{ placeholder: "Search or Add", type: "text" }
      - else
        %button.navbar-toggle{"data-target" => ".navbar-inverse-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
    .navbar-collapse.collapse.navbar-inverse-collapse
      - if current_user
        %p.navbar-text.navbar-right
          Logged in as #{current_user.name}
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "Log out", sign_out_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            = link_to "Log in", new_session_path
:css
  .navbar .navbar-text {
    margin-top: 15px;
    margin-bottom: 15px;
  }
  .navbar-form {
    border-top: none;
    border-bottom: none;
    -webkit-box-shadow: none;
    box-shadow: none;
  }